# These substitutions allow the end user to override certain values
substitutions:
  name: "supramatic-e3"
  friendly_name: "SupraMatic E3"
  state: "State"
  opening: "Opening"
  closing: "Closing"
  open: "Open"
  closed: "Closed"
  stopped: "Stopped"
  venting: "Venting"
  error: "Error"
  relay_state: "Relay state"
  got_valid_broadcast: "Valid Status received" 
  error_state: "Error State" 
  prewarn_state: "Prewarn State" 
  light: "${friendly_name} Light"
  sw_vent: "${friendly_name} Venting" 
  sw_light: "Switch Light" 
  btn_vent: "${friendly_name} Vent" 
  btn_impulse: "${friendly_name} Impulse" 

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

esp32:
  board: esp32dev # set your board
  framework:
    type: esp-idf # mandatory for esp version

external_components:
    - source: github://14yannick/hoermann_door
      refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_key_e3_supra
  
ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: WARN
  baud_rate: 0 # Disable Serial logging to avoid conflict with uart bus on UART0

uart:
  id: uart_bus
  baud_rate: 19200
  rx_pin: 16
  tx_pin: 17

uapbridge_esp:
  id: garage_door_comp
  # rts_pin: 4 # this can be set, if needed for the connected hardware
  uart_id: uart_bus
  auto_correction: true

cover:
  - platform: uapbridge
    name: ${friendly_name}
    device_class: garage

switch:
  - platform: uapbridge
    venting_switch:
      id: venting_switch
      name: "${sw_vent}"
#uncomment if you want to use the switch insteat of the light component for light
#    light_switch:
#      id: light_switch
#      name: "${sw_light}"

binary_sensor:
  - platform: uapbridge
    relay_state:
      name: "${relay_state}"
    error_state:
      name: "${error_state}"
    prewarn_state:
      name: "${prewarn_state}"
    got_valid_broadcast:
      name: "${got_valid_broadcast}"

output:
  - platform: uapbridge
    id: gd_light

light:
  - platform: uapbridge
    id: my_light
    name: "${light}"
    output: gd_light

text_sensor:
  - platform: uapbridge
    id: garage_door_state
    name: "${state}"
#    filters:
#      - substitute:
#        - "Opening -> ${opening}"
#        - "Closing -> ${closing}"
#        - "Open -> ${open}"
#        - "Closed -> ${closed}"
#        - "Stopped -> ${stopped}"
#        - "Venting -> ${venting}"
#        - "Error -> ${error}"

button:
  - platform: uapbridge
    vent_button:
      id: button_vent
      name: "${btn_vent}"
    impulse_button:
      id: button_impulse
      name: "${btn_impulse}"

#optional BME Sensor
#i2c:
#  - id: bus_1
#    sda: SDA
#    scl: SCL
#    scan: true
#sensor:
#  - platform: bme280_i2c
#    temperature:
#      name: "BME280 Temperature"
#    pressure:
#      name: "BME280 Pressure"
#    humidity:
#      name: "BME280 Humidity"
#    address: 0x76
#    update_interval: 10min